#! /bin/sh
sxhkd &
picom --experimental-backends &
nitrogen --restore &
#solaar &
copyq &
nm-applet &
xsetroot -cursor_name left_ptr &
flashfocus &

# Monitors

#xrandr --output HDMI-A-0 --primary --mode 3840x2160 --pos 0x0 --rotate normal --output DVI-D-0 --mode 1920x1080 --pos 3840x0 --output DisplayPort-0 --off --output DisplayPort-1 --off
#xrandr --output HDMI-A-0 --primary --auto --output DVI-D-0 --auto --right-of HDMI-A-0
xrandr --output DisplayPort-0 --primary --mode 3840x2160 --pos 0x0 --rotate normal --output HDMI-A-0 --mode 3840x2160 --pos 3840x0 --rotate normal --output DVI-D-0 --off

bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 6 7 8 9 10

#Polybar
~/.config/polybar/launch.sh

# Configuration
bspc config border_width        1
bspc config window_gap          6
#bspc config -m DVI-D-0 window_gap 0
bspc config top_padding         -1
bspc config bottom_padding	-4	
bspc config right_padding	-4	
bspc config left_padding	-4	
bspc config single_monocle	false
bspc config click_to_focus	button1
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance	 true
bspc config focus_follows_pointer true
bspc config history_aware_focus	true
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true
bspc config pointer_follows_focus	true
#bspc config pointer_follows_monitor	true

# Coloring 
#bspc config normal_border_color	"#4c566a"
bspc config presel_feedback_color	"#5f87af"
#orange
#bspc config focused_border_color	"#9e3605"
#blue
#bspc config focused_border_color	"#0b5394"
#orange gruvbox
bspc config focused_border_color	"#d75f00"
#gruvbox
#bspc config focused_border_color	"#ffd7af"
#gruvbox blue
#bspc config focused_border_color	"#87afaf"
bspc config active_border_color		"#5f87af"
bspc config urgent_border_color		"#dd2727"

#Polybar hidden when fullscreen
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DVI-D-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)

# Rules
#bspc rule -a Gimp desktop='^2:^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Thunar state=floating
bspc rule -a Galculator state=floating
#bspc rule -a vlc state=floating
#bspc rule -a Evolution-alarm-notify state=floating
#bspc rule -a Yad state=floating
bspc rule -a Htop state=floating rectangle=1011x1024+2428+284
#bspc rule -a Zathura desktop='^9' state=tiled follow=on
bspc rule -a Spotify desktop='^4'
bspc rule -a Vncviewer desktop='^5' follow=on
bspc rule -a 'Microsoft Teams - Preview' desktop='^10' follow=off
bspc rule -a obs desktop='^4' state=tiled
bspc rule -a AUR state=floating rectangle=651x564+2397+23
bspc rule -a org.remmina.Remmina state=tiling desktop='^5'
bspc rule -a Dragon-drag-and-drop sticky=on
bspc rule -a copyq  state=floating 

# Scratchpad (term alacritty)
bspc rule -a dropdown sticky=on state=floating hidden=on rectangle=902x458+877+324
alacritty --config-file $HOME/.config/alacritty/dropdown.yml --class dropdown,dropdown &
