#! /bin/sh
sxhkd &
picom &
nitrogen --restore &
#solaar &
copyq &
nm-applet &
xsetroot -cursor_name left_ptr &

# Monitors
xrandr --output HDMI-A-0 --primary --mode 2560x1080 --pos 0x0 --rotate normal --output DVI-D-0 --mode 1920x1080 --pos 2560x0 --rotate normal --output DisplayPort-0 --off --output DisplayPort-1 --off
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 
bspc monitor DVI-D-0 -d 7 8 9 10 11 12
#bspc monitor DisplayPort-1 -d 1

#Polybar
~/.config/polybar/launch.sh

# Configuration
bspc config border_width        2
bspc config window_gap          10
bspc config -m DVI-D-0 window_gap 3
bspc config -m DisplayPort-1 window_gap 3
bspc config top_padding         0
bspc config bottom_padding	0	
bspc config right_padding	0	
bspc config left_padding	0	
bspc config single_monocle	false
bspc config click_to_focus	button1
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance	 true
bspc config focus_follows_pointer true
bspc config history_aware_focus	true
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true
#bspc config pointer_follows_focus	true
bspc config pointer_follows_monitor	true

# Coloring 
#bspc config normal_border_color	"#4c566a"
bspc config presel_feedback_color	"#5f87af"
bspc config focused_border_color	"#9e3605"
bspc config active_border_color		"#5f87af"
bspc config urgent_border_color		"#dd2727"

#Polybar hidden when fullscreen
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DVI-D-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)

# Rules
#bspc rule -a Gimp desktop='^2:^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Thunar state=floating
bspc rule -a Galculator state=floating
bspc rule -a vlc state=floating
bspc rule -a Evolution-alarm-notify state=floating
bspc rule -a Yad state=floating
bspc rule -a Htop state=floating
bspc rule -a Zathura desktop='^8' state=tiled follow=on
bspc rule -a Spotify desktop='^10'
bspc rule -a 'Microsoft Teams - Preview' desktop='^7'
